pipeline {
    agent any
         tools {
             maven 'maven3'
         }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
        stage('Deploy') {
            steps {
                deploy adapters: [
                    tomcat9(credentialsId: '7fe21514-6478-467f-bb64-86c2867e24b3', 
                            path: '', url: 'http://18.212.151.58:8080/')
                    ], contextPath: null, war: '**/*.war'
    }
}
